// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBED6qRAJVS11i_IUlEx-QJUbFEX9HtSrA',
    appId: '1:898531117301:web:11c0c575cf6c25e73c5dbc',
    messagingSenderId: '898531117301',
    projectId: 'fitness-app-c1424',
    authDomain: 'fitness-app-c1424.firebaseapp.com',
    storageBucket: 'fitness-app-c1424.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMPJgJXa35am6O3bvT2MdXibh0IZQxfCM',
    appId: '1:898531117301:android:79f7e86f0039c31e3c5dbc',
    messagingSenderId: '898531117301',
    projectId: 'fitness-app-c1424',
    storageBucket: 'fitness-app-c1424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeo_Oz2d30wMdDKhv1shW0ZJMJFP3wA8',
    appId: '1:898531117301:ios:0f4d48a0d5023a8e3c5dbc',
    messagingSenderId: '898531117301',
    projectId: 'fitness-app-c1424',
    storageBucket: 'fitness-app-c1424.appspot.com',
    iosClientId: '898531117301-44kir36bsldd44f33a7ajucrf3774334.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUeo_Oz2d30wMdDKhv1shW0ZJMJFP3wA8',
    appId: '1:898531117301:ios:0f4d48a0d5023a8e3c5dbc',
    messagingSenderId: '898531117301',
    projectId: 'fitness-app-c1424',
    storageBucket: 'fitness-app-c1424.appspot.com',
    iosClientId: '898531117301-44kir36bsldd44f33a7ajucrf3774334.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittnessTracker',
  );
}
